# Generated by Django 4.0.2 on 2022-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_image_food_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='food_group',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('grain', 'Grain'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('unknown', 'Unknown')], max_length=100),
        ),
    ]
