# Generated by Django 4.0.2 on 2022-03-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_image_food_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='updated_on',
        ),
    ]
