# Generated by Django 4.0.2 on 2022-03-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_image_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
