# Generated by Django 4.0.2 on 2022-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='food_group',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=100),
        ),
    ]
